# Generated by Django 4.2 on 2023-04-06 00:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_publicadosmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='posts', variations={'thumb': {'crop': True, 'height': 440, 'width': 440}}, verbose_name='Imagem'),
        ),
    ]
